immutables/immutables

value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/ValueType.java
merge improved `Builder.from` method which can accept multiples supertypes (traits).
=> From super types

generator-processor/pom.xml, generator-processor/src/org/immutables/generator/processor/Processor.java, metainf/pom.xml, metainf/src/org/immutables/metainf/processor/Processor.java
using special-built version of Metainf.Service that we have
=> Decom of auto-service )

value-fixture/src/org/immutables/fixture/style/OptionalWithNullable.java, value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/OkJsons.generator, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value/src/org/immutables/value/Value.java
this fixes #152 @augustotravillio 
Let me know if I've missed something terrifying, or if I've done something out of the standard.  I've not used the generators before.
=> add support for making optionals handle null values.

generator/src/org/immutables/generator/PostprocessingMachine.java, generator/test/org/immutables/generator/PostprocessingMachineTest.java
Fix for https://github.com/immutables/immutables/issues/154
=> fix for classes with underscores

generator/src/org/immutables/generator/SourceExtraction.java, value-fixture/src/nonimmutables/SampleRuntimeException.java, value-fixture/src/org/immutables/fixture/style/SpecifiedException.java, value-fixture/test/org/immutables/fixture/style/SpecifiedExceptionTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value/src/org/immutables/value/Value.java
Added support for throwing a default `? extends RuntimeException` on build and deserialization; also adding support for passing a `Function<String, ? extends RuntimeException>` so that the user can call build with a specific exception to throw when they want something other than the default.
=> Add choice for exceptions

value-processor/src/org/immutables/value/processor/meta/Annotations.java
Rosetta Annotations, are all annotated with `@RosettaAnnotation`; other libraries do this for good housekeeping.  I have made a change here so that our style can have:
`additionalJsonAnnotations = { RosettaAnnotation.class }`
so that when Rosetta adds more annotations we don't need to add them to the style. 
Hope it makes sense
=> Add support for annotation groups

value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/OkJsons.generator, value-processor/src/org/immutables/value/processor/Repositories.generator
These changes provide corrections for the the JavaDoc generated for types.
=> Adjust grammar, wording, etc, of generated JavaDoc

value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
Pull request with fix for issue #224.
=> Fix 224 pull request

value-fixture/src/org/immutables/fixture/style/OptionalWithNullable.java, value-fixture/test/org/immutables/fixture/ValuesTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Modifiables.generator
@elucash currently the setter accepts `@Nullable int value`, and should accept `@Nullable Integer value`
=> Don't unbox types in setters for optionalAcceptNullable.

value-processor/src/org/immutables/value/processor/meta/TypeStringProvider.java
=> add some details as to the failure, so people can fix it.

value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
Implement unset functions to reset variables to their initial values.
=> Address issue #420

.travis.yml
When the automated build for my previous PR (#457) failed, I noticed that [the build fails for all PRs](https://travis-ci.org/immutables/immutables/pull_requests). This change should fix that. (But we'll only know for sure once I submit this PR...)
=> Don't deploy PRs, just package them

value-processor/src/org/immutables/value/processor/Immutables.generator
=> use Double.valueOf() instead of new Double()

value-fixture/src/org/immutables/fixture/modifiable/Companion.java, value-fixture/src/org/immutables/fixture/modifiable/differentPackage/ReferenceDifferentPackage.java, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/meta/Constitution.java
As mentioned in #541 should the typeModifiable have some kind of FQN value.
This PR adds absolute and absoluteRaw fields to typeModifiable and a simple test to fixture.
=> #541 Modifiable with deepImmutablesDetection in different packages

value-processor/src/org/immutables/value/processor/Immutables.generator
Replacing Java 7 String switch statements (similar to my earlier PR #43).
=> Support Java 6 runtime when using serial module

gson/test/org/immutables/gson/adapter/MapTest.java, gson/test/org/immutables/gson/stream/JaxrsTest.java, gson/test/org/immutables/gson/stream/Resource.java
=> GsonMessageBodyProvider unable to serialize Boolean

mongo/pom.xml, mongo/src/org/immutables/mongo/repository/Repositories.java, mongo/src/org/immutables/mongo/repository/internal/BsonEncoding.java, mongo/test/org/immutables/mongo/fixture/BasicMongoOperationsTest.java, mongo/test/org/immutables/mongo/fixture/MongoContext.java
Added support for Fongo database.
=> added support for Fongo (in-memory MongoDB)

mongo/src/org/immutables/mongo/types/Binary.java, mongo/test/org/immutables/mongo/fixture/BasicMongoOperationsTest.java, mongo/test/org/immutables/mongo/fixture/Item.java, mongo/test/org/immutables/mongo/fixture/SimpleUpdaterTest.java, value-processor/src/org/immutables/value/processor/Repositories.generator
This operation overrides the whole array instead of partially updating.
=> added $set operator for sub-arrays of a document

value/src/org/immutables/value/Value.java
Opening this @elucash to make sure we're on the same page about the API.
If this looks good to you, it would be helpful to merge this, do a release, so I can update value-processor/pom.xml.
=> Nested builder detection API.

value-processor/src/org/immutables/value/processor/Immutables.generator
see http://errorprone.info/api/latest/com/google/errorprone/annotations/Var.html
and http://errorprone.info/bugpattern/Var
Fixes https://github.com/immutables/immutables/issues/716
Signed-off-by: Michael Vorburger <vorburger@redhat.com>
=> Use error-prone @Var in hashCode()

value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
=> Resolve #784 unchecked cast of java.util.Optional parameters 

mongo/test/org/immutables/mongo/fixture/criteria/Person.java, mongo/test/org/immutables/mongo/fixture/criteria/PersonCriteriaTest.java, value-processor/src/org/immutables/value/processor/Repositories.generator
Add pattern matching criteria methods (*StartsWith, *Matches, *NotMatches) for Optional<String> attributes.
#813
=> Add pattern criteria for Optional<String> attributes

gson/test/org/immutables/gson/adapter/Optionals.java, gson/test/org/immutables/gson/adapter/OptionalsTest.java, value-fixture/src/org/immutables/fixture/jdkonly/HasOptionalToFloat.java, value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
=> Fix optional serialization

gson/pom.xml
Same version should be used across all modules
=> Update jackson-core version in gson module (2.8.5 -> 2.8.11)

mongo/pom.xml
=> Upgrade mongo java driver: 3.5.0 -> 3.10.1

criteria/common/src/org/immutables/criteria/DocumentCriteria.java, criteria/common/src/org/immutables/criteria/constraints/Expressional.java
DocumentCriteria doesn't extend Expression anymore instead implements Expressional.
=> Introduce Expressional interface for more composability

criteria/mongo/pom.xml, func/pom.xml, gson/pom.xml, mongo/pom.xml, pom.xml, utility/pom.xml
Some modules share same dependencies (eg. jackson) better to have same versions.
=> Add maven version properties for shared libraries in pom.xml (eg. guava.version)

value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
New function will be used in templates to build nested criterias.
Eugene showed an example in #943
=> Add criteria detection in ValueAttribute

criteria/common/src/org/immutables/criteria/InMemoryExpressionEvaluator.java
valid "boolean" values are `true / false / unknown` (because of `NULL`s)
=> Use Three-Valued-Logic (3VL) for our in-memory evaluator

criteria/common/src/org/immutables/criteria/constraints/CollectionCriteria.java, criteria/common/src/org/immutables/criteria/constraints/ObjectCriteria.java, criteria/common/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/common/test/org/immutables/criteria/Person.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java, criteria/common/test/org/immutables/criteria/TypeHolder.java, criteria/common/test/org/immutables/criteria/TypeHolderTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Add TypeHolder class with all basic (scala) types
=> Criteria. Support for scalar elements like Optional<Boolean> etc.

criteria/common/src/org/immutables/criteria/constraints/CollectionCriteria.java, criteria/common/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
```java
S none(Consumer<C> consumer) {
// ....
}
```
=> Criteria. Type inside Consumer<C> should not terminate in root (R)

criteria/common/src/org/immutables/criteria/constraints/CollectionCriteria.java, criteria/common/src/org/immutables/criteria/constraints/CriteriaContext.java, criteria/common/src/org/immutables/criteria/constraints/DnfExpression.java, criteria/common/src/org/immutables/criteria/constraints/Expressions.java, criteria/common/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/common/test/org/immutables/criteria/PersonTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Allow the following queries (only optionals for now):
```java
crit.lastName.value().isEqualTo("Smith")
crit.lastName.value(v -> v.isEqualTo("Smith"))
```
=> Criteria. Working implementation of `OptionalCriteria.value()` with lambdas

criteria/common/pom.xml, criteria/common/src/org/immutables/criteria/Repository.java, criteria/elasticsearch/pom.xml, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/AsyncRestPublisher.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/Elasticsearch.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchRepository.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/Publishers.java, criteria/elasticsearch/test/log4j2.xml, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticModel.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticsearchOps.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/EmbeddedElasticsearchNode.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/EmbeddedElasticsearchResource.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/IntegrationTest.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoRepository.java, pom.xml
1. Add embedded ES instance for tests
2. Add simple reactive publisher implementation
3. Add simple tests for select all
=> Criteria. Initial cut for Elasticsearch adapter

criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/Elasticsearch.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchQueryVisitor.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchRepository.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/Publishers.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/QueryBuilders.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/IntegrationTest.java
Support EQUAL and NOT_EQUAL operator
=> Criteria. Elasticsearch adapter. Basic querying capabilities.

criteria/common/test/org/immutables/criteria/PersonTest.java, criteria/elasticsearch/pom.xml, criteria/inmemory/README.md, criteria/inmemory/pom.xml, criteria/inmemory/src/org.immutables.criteria.inmemory/InMemoryExpressionEvaluator.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryExpressionEvaluatorTest.java, criteria/pom.xml
In future we may provide inmemory Repository
=> Criteria. Extract inmemory evaluator into a separate sub-module: inmemory

criteria/common/src/org/immutables/criteria/matcher/CollectionMatcher.java, criteria/common/src/org/immutables/criteria/matcher/NotMatcher.java, criteria/common/src/org/immutables/criteria/matcher/StringMatcher.java, criteria/common/test/org/immutables/criteria/PersonTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Allow negations like `crit.not(f -> f.names.hasSize(2))`
=> Criteria. Add NOT matcher

criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchQueryVisitor.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchRepository.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticsearchIntegrationTest.java
Support comparisons and IN / NOT IN operators
=> Criteria. Improve expression evaluation for ElasticSearch

criteria/README.md, criteria/common/src/org/immutables/criteria/expression/AbstractExpressionVisitor.java, criteria/common/src/org/immutables/criteria/expression/Visitors.java, criteria/geode/README.md, criteria/geode/pom.xml, criteria/geode/src/org/immutables/criteria/geode/GeodeQueryVisitor.java, criteria/geode/src/org/immutables/criteria/geode/GeodeRepository.java, criteria/geode/src/org/immutables/criteria/geode/Geodes.java, criteria/geode/test/org/immutables/criteria/geode/GeodeIntegrationTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodeResource.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoQueryVisitor.java, criteria/mongo/src/org/immutables/criteria/mongo/Mongos.java, criteria/pom.xml, pom.xml
Add adapter for [Apache Geode](https://geode.apache.org/)
=> Criteria. Basic support for Geode

criteria/mongo/pom.xml, criteria/mongo/src/org/immutables/criteria/mongo/Wrapper.java, criteria/mongo/src/org/immutables/criteria/mongo/bson4jackson/BsonGenerator.java, criteria/mongo/src/org/immutables/criteria/mongo/bson4jackson/BsonParser.java, criteria/mongo/src/org/immutables/criteria/mongo/bson4jackson/JacksonCodecs.java, criteria/mongo/src/org/immutables/criteria/mongo/bson4jackson/package-info.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java, criteria/mongo/test/org/immutables/criteria/mongo/bson4jackson/BsonParserTest.java
Need support for jackson in mongo (currently there is no immutable specific abstraction for JSON)
=> Copy bson4jackson source code from legacy mongo module

criteria/common/src/org/immutables/criteria/internal/Reactive.java, criteria/common/src/org/immutables/criteria/internal/Service.java, criteria/common/src/org/immutables/criteria/internal/package-info.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchRepository.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoRepository.java
Move Publishers class into internal package
=> Criteria. Introduce Service interface as internal API

criteria/common/src/org/immutables/criteria/Repository.java, criteria/common/src/org/immutables/criteria/internal/Query.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticBackend.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticsearchIntegrationTest.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoBackend.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
Mongo / Elastic and Geode have been migrated to Backend
=> Migrate generated repositories to use Backend interface

criteria/common/test/org/immutables/criteria/personmodel/PersonGenerator.java, criteria/common/test/org/immutables/criteria/personmodel/PersonGeneratorTest.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java
Only set fields you're interested in and skip required ones
=> Add PersonGenerator class to simplify test object creation

criteria/common/src/org/immutables/criteria/Repository.java, criteria/common/src/org/immutables/criteria/adapter/Operations.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoBackend.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
For future compatibility with key-value stores like Geode / ConcurrentMap etc.
=> Allow insertion of documents (in Repositories) with and without keys

criteria/elasticsearch/pom.xml, criteria/geode/pom.xml, criteria/mongo/pom.xml
change maven scope from `test` to default (`compile`)
=> Add rxjava2 dependency to adapter (not common) module(s)

criteria/common/src/org/immutables/criteria/AsyncRepository.java, criteria/common/src/org/immutables/criteria/Criterias.java, criteria/common/src/org/immutables/criteria/ReactiveRepository.java, criteria/common/src/org/immutables/criteria/Repository.java, criteria/common/src/org/immutables/criteria/SyncRepository.java, criteria/common/src/org/immutables/criteria/adapter/InternalReader.java, criteria/common/src/org/immutables/criteria/adapter/InternalWatcher.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
A step towards different types of repositores (blocking / asynchronous etc.)
=> Add Sync / Async / Reactive repositories

criteria/common/src/org/immutables/criteria/ReactiveRepository.java, criteria/common/src/org/immutables/criteria/Repository.java, criteria/common/src/org/immutables/criteria/SyncRepository.java, criteria/common/src/org/immutables/criteria/WriteResult.java, criteria/common/src/org/immutables/criteria/adapter/Operations.java, criteria/common/src/org/immutables/criteria/adapter/UnknownWriteResult.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/test/org/immutables/criteria/geode/GeodeIntegrationTest.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoBackend.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
Allow more fine-grained statistics after a write operation
=> Introduce WriteResult interface which replaces Repository.Success

criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/src/org/immutables/criteria/geode/GeodeQueryVisitor.java, criteria/geode/src/org/immutables/criteria/geode/Geodes.java, criteria/geode/src/org/immutables/criteria/geode/OqlWithVariables.java, criteria/geode/test/org/immutables/criteria/geode/GeodePersonTest.java
Bind variables can't be used in CQ
=> Geode use bind variables when possible

criteria/common/src/org/immutables/criteria/matcher/AndMatcher.java, criteria/common/src/org/immutables/criteria/matcher/Matchers.java, criteria/common/src/org/immutables/criteria/matcher/OrMatcher.java, criteria/common/test/org/immutables/criteria/ExpressionAsStringTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Allow users to combine existing criterias with ANDs / ORs logical operations
=> Add instance methods AND / OR to generated criteria

criteria/common/test/org/immutables/criteria/ExpressionAsStringTest.java, criteria/common/test/org/immutables/criteria/TypeHolderTest.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/common/test/org/immutables/criteria/personmodel/PersonTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticModelTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodeCqTest.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryExpressionEvaluatorTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
It is easier to chain with DSL
=> Add public static field to generated Criteria instead of factory method (aka create())

criteria/common/src/org/immutables/criteria/Repository.java, criteria/common/src/org/immutables/criteria/adapter/InternalReader.java, criteria/common/src/org/immutables/criteria/expression/Collation.java, criteria/common/src/org/immutables/criteria/expression/Ordering.java, criteria/common/src/org/immutables/criteria/expression/Query.java, criteria/common/src/org/immutables/criteria/matcher/ComparableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaContext.java, criteria/common/src/org/immutables/criteria/matcher/OrderMatcher.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchBackend.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticPersonTest.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/test/org/immutables/criteria/geode/GeodePersonTest.java, criteria/inmemory/src/org.immutables.criteria.inmemory/InMemoryBackend.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoBackend.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoPersonTest.java
List of backends which support sorting :
* Mongo
* Elasticsearch
* Geode
InMemoryBackend explicitly throws exception.
=> Add support for orderBy (sorting) functionality

value-processor/pom.xml
=> Upgrade immutables bootstrap jar (from value-processor) 2.5.6 -> 2.7.5

criteria/common/src/org/immutables/criteria/matcher/BooleanMatcher.java, criteria/common/src/org/immutables/criteria/matcher/ComparableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaCreator.java, criteria/common/src/org/immutables/criteria/matcher/IterableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/Matchers.java, criteria/common/src/org/immutables/criteria/matcher/ObjectMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalMatcher.java, criteria/common/src/org/immutables/criteria/matcher/StringMatcher.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java
Each matcher is responsible for its own factory
=> Move factory methods (CriteriaCreator) directly into matchers

criteria/common/pom.xml, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveReader.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveRepository.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveWatcher.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveWritable.java, criteria/common/src/org/immutables/criteria/repository/sync/SyncReader.java, criteria/common/src/org/immutables/criteria/repository/sync/SyncWritable.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/common/test/org/immutables/criteria/personmodel/CriteriaChecker.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
Make sync implementation depend on reactive API
=> Move reactive implementations into separate package.

criteria/common/src/org/immutables/criteria/Criteria.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveWatchable.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveWritable.java, criteria/common/test/org/immutables/criteria/personmodel/Person.java, criteria/common/test/org/immutables/criteria/processor/CriteriaMatcherTest.java, criteria/common/test/org/immutables/criteria/processor/RepositoryTest.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaMirrors.java, value-processor/src/org/immutables/value/processor/meta/MoreElements.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value-processor/src/org/immutables/value/processor/meta/ValueTypeRepository.java
Introduce several javax.lang.model helper methods.
Add ValueTypeRepository class with repository creation logic
Change repository implementation to delegate to Readable / Writable / Watchable etc.
=> Support for facets aka customizable repository

criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveReadable.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator, value-processor/src/org/immutables/value/processor/meta/MoreElements.java, value-processor/src/org/immutables/value/processor/meta/MoreTypes.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value-processor/src/org/immutables/value/processor/meta/ValueTypeRepository.java
Compared to previous iteration only implemented interfaces were generated (not their methods).
List of facets (properties) are identified at compile-time
=> Generate repository methods based on facets (from annation)

generator/src/org/immutables/generator/ExtensionLoader.java
Changed how the META-INF/annotations/org.immutables.value.immutable is read - disabled URLConnection caching.
https://github.com/immutables/immutables/issues/1060
=> Fix for jar leak on gradle deamon

value-fixture/src/org/immutables/fixture/modifiable/DefaultMap.java, value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
=> Set optBits for Modifiable, Default maps

value-fixture/src/org/immutables/fixture/builder/functional/AttributeBuilderBuilderI.java, value-fixture/src/org/immutables/fixture/builder/functional/AttributeBuilderValueI.java, value-fixture/test/org/immutables/fixture/builder/AttributeBuilderTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
Currently you get exceptions when using attributeBuilderDetection=true and have an Optional immutable.
=> Add support for optional attributeBuilders.

criteria/geode/src/org/immutables/criteria/geode/GeodeQueryVisitor.java, criteria/geode/src/org/immutables/criteria/geode/OqlGenerator.java, criteria/geode/test/org/immutables/criteria/geode/GeodePersonTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodeQueryVisitorTest.java, criteria/geode/test/org/immutables/criteria/geode/OqlGeneratorTest.java
Adds support to OQL generator for Iterable queries
=> Support OQL Iterable queries

criteria/common/pom.xml, criteria/common/test/org/immutables/criteria/processor/CriteriaModelProcessorTest.java, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java
=> Adds support for Fugue Option to CriteriaModel

bom/pom.xml, pom.xml
#1187 I had the time to do the required changes needed for a Bill of Materials as described with the issue.
Regards
Joke
=> Added Bill of Materials (BoM) artifact

android-stub/pom.xml, criteria/common/pom.xml, criteria/elasticsearch/pom.xml, criteria/geode/pom.xml, criteria/inmemory/pom.xml, criteria/mongo/pom.xml, criteria/reactor/pom.xml, criteria/rxjava2/pom.xml, criteria/sql/pom.xml, generator-fixture/pom.xml, generator-processor/pom.xml, processor-testlib/pom.xml, value-fixture/pom.xml
Fixes immutables/immutables#1223
=> resolve auto-module-name generation

criteria/common/src/org/immutables/criteria/repository/sync/SyncFetcherDelegate.java, criteria/inmemory/src/org/immutables/criteria/inmemory/ExpressionInterpreter.java, criteria/pom.xml, generator-processor/pom.xml, generator/pom.xml, gson/pom.xml, metainf/pom.xml, mongo/test/org/immutables/mongo/bson4gson/JavaTimeTest.java, pom.xml, value-fixture/pom.xml, value-fixture/src/org/immutables/fixture/custann/CustomEncl.java, value-fixture/src/org/immutables/fixture/custann/CustomImmutables.java, value-fixture/test/org/immutables/fixture/generatorext/RewriteTest.java
I know you didn't ask for it, but now you have it.
I made Immutables build successfully not only on JDK8 but on any other JDK after 8. Your CI shows everything green.
There are some caveats though.
=> Immutables to build on all JDKs 8+

generator/src/org/immutables/generator/AbstractGenerator.java, generator/src/org/immutables/generator/ExtensionLoader.java, generator/src/org/immutables/generator/StaticEnvironment.java, value-fixture/pom.xml, value-fixture/src/org/immutables/fixture/custann/CustomEncl.java, value-fixture/src/org/immutables/fixture/custann/CustomImmutables.java
Sorry I broke some extensions. I'm bringing some of them back.
The only problem left is disabled test in https://github.com/immutables/immutables/blob/master/value-fixture/test/org/immutables/fixture/generatorext/RewriteTest.java
=> Fix some previously broken extensions support.

data/test/org/immutables/data/Dtt.java, serial/test/org/immutables/serial/fixture/NullableCollections.java, serial/test/org/immutables/serial/fixture/SerialTest.java, value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/encoding/defs/CompactDate.java, value-processor/src/org/immutables/value/processor/Datatypes.generator, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/encode/Code.java, value-processor/src/org/immutables/value/processor/encode/EncodedElement.java, value-processor/src/org/immutables/value/processor/encode/Renderers.generator
=> Fresh fixes

.github/workflows/ci.yml, criteria/mongo/pom.xml, criteria/pom.xml, generator/pom.xml, mongo/pom.xml, pom.xml, value-fixture/pom.xml
Making some progress towards Java 17 support.
Right now it only compiles with Java 16. Addresses an issue from https://github.com/immutables/immutables/issues/1283
=> Java 16 compat

.github/workflows/ci.yml, criteria/mongo/pom.xml, criteria/pom.xml, generator/pom.xml, mongo/pom.xml, pom.xml, value-fixture/pom.xml
Continuation of https://github.com/immutables/immutables/pull/1326
Looks like everything works on 17-ea also.
=> Java 17 compat.

README.md
Demonstrates that the "addCounts" creates a list, and that the description, though an optional, can be set with just a String.
=> Add sample code to demonstrate getter usage

.github/workflows/ci.yml, criteria/mongo/pom.xml, criteria/pom.xml, generator-fixture/pom.xml, generator-processor/pom.xml, metainf/pom.xml, mirror/pom.xml, mongo/pom.xml, pom.xml, value-fixture/pom.xml, value-processor/pom.xml
- Test Immutables using Java 17 target on Java 17
- Move opens close to build definitions that actually need them.
=> Use Java 17 target on Java 17.

pom.xml
Reverts immutables/immutables#1414
=> Revert "fix(sec): upgrade org.apache.geode:geode-core to 1.15.0"

pom.xml, value-fixture/test/org/immutables/fixture/modifiable/BeanFriendlyTest.java
Replaces #1421 with test change
=> guava upgrade to 30.0-jre

value-processor/src/org/immutables/value/processor/Immutables.generator
=> Fix #1424 - redundant null check in JDK maps

builder/test/org/immutables/builder/fixture/GenericsImprovisedFactories.java, value-processor/src/org/immutables/value/processor/meta/TypeStringProvider.java
See https://github.com/immutables/immutables/issues/1531
=> Fix a bug with type annotation handling
