immutables/immutables

value-fixture/src/nonimmutables/AdditionalJacksonAnnotation.java, value-fixture/src/org/immutables/fixture/jackson/JacksonMappedWithExtraAnnotation.java, value-fixture/test/org/immutables/fixture/jackson/JsonAnnotationTest.java, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value/src/org/immutables/value/Value.java
this is for the addition to #150 so we can pass extra annotations down to the Json layer.  The reason we want this is because we use [Rosetta](https://github.com/HubSpot/Rosetta) and need to pass these annotations for the rosetta mapper.
=> add ability to pass annotations down to the json layer.

value-fixture/src/org/immutables/fixture/jackson/JacksonMappedWithExtraAnnotation.java, value-fixture/test/org/immutables/fixture/jackson/JsonAnnotationTest.java, value-processor/src/org/immutables/value/processor/meta/Annotations.java
We annotate some of our methods with `@JsonSerialize` as the objects need to be serialised a different way, this also needs to be passed down to the json class
=> add the databind annotation to the json object.

value-fixture/src/org/immutables/fixture/PrivateNoArgConstructor.java, value-fixture/test/org/immutables/fixture/PrivateDefaultConstructorTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java, value-processor/src/org/immutables/value/processor/meta/ValueTypeComposer.java, value/src/org/immutables/value/Value.java
Allows supporting frameworks that build objects reflectively, most notably ORMs.
=> Added support for optional generation of a private noarg default constructor

value-processor/src/org/immutables/value/processor/Immutables.generator
I'm getting the below javadoc error in my Immutable generated classes.
```
error: reference not found
* @throws exception {@code java.lang.IllegalStateException} if any required attributes are missing
^
```
=> Fix javadoc throws syntax

cases/pom.xml, cases/test/org/immutables/moshi/Adapt.java, cases/test/org/immutables/trees/ast/SampleTree.java, value-fixture/pom.xml, value-fixture/src/org/immutables/fixture/SillyStructureWithId.java, value-fixture/src/org/immutables/fixture/jdkonly/UsingAllOptionals.java, value-fixture/src/org/immutables/fixture/modifiable/Companion.java, value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/OkJsons.generator, value-processor/src/org/immutables/value/processor/Transformers.generator, value-processor/src/org/immutables/value/processor/meta/AttributeTypeKind.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
Atlasssian Fugue is a nice little library that is an functional extension of Guava and/or Java 8. Fugue contains an Option class which is an alternative to the Optional type class of Guava and/or Java 8.
This pull request adds the same support for the Fugue Option class as the other Optional classes.
Atlassian just released Fugue 3 which uses a different package (io.atlassian.fugue) then Fugue 2 and older (com.atlassion.fugue). This pull requests add support for both versions.
=> Added support for the Atlassian Fugue Option class

gson/src/org/immutables/gson/stream/JsonParserReader.java
This change fixes deserialization of &lt;Optional&gt;TimeUnit.
See discussion: https://groups.google.com/forum/#!topic/immutables/CCLcdHRgpAM
=> fixed bug deserializeing VALUE_EMBEDDED_OBJECT json types

value-processor/src/org/immutables/value/processor/Immutables.generator
Fix https://github.com/immutables/immutables/issues/309 by making initShim fields transient
=> Make initShim fields transient

value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
I've corrected the use of "loosing" to "losing" in this warning message:
> Generic wildcards are not supported, so the container attribute _loosing_ its special treatment
=> Correct spelling mistake in warning message

value-processor/src/org/immutables/value/processor/meta/ValueType.java
Fixed the generation of constructor annotations by using the element type CONSTRUCTOR instead of METHOD.
=> #396 Fix for constructor annotations with @Target(CONSTRUCTOR)

value/src/org/immutables/value/Value.java
* fix typo 's/instanse/instace/' on
`Value.Style.toImmutable()`
* replace (accidental) code comment by
Javadoc method description on
`Value.Style.typeWith()`
=> fix Javadoc

pom.xml
This is a non-functional change that should make it more attractive for users of Eclipse to contribute to this project. As the `pom.xml` comment explains, this change makes explicit that this project heavily relies on two additional build source paths:
* `${project.build.directory}/generated-sources/annotations`
* `${project.build.directory}/generated-test-sources/test-annotations`
By explicitly listing these using the `build-helper-maven-plugin` they'll automatically be picked up by modern versions of Eclipse, so that the user doesn't have to spend several minutes manually adding these directories to the build path. Tested with the latest version of Eclipse and M2Eclipse (4.6.1 and 1.70, respectively).
NB: Perhaps this trick should also be documented on https://immutables.github.io/?
=> Provide a better experience to Eclipse users

value-fixture/pom.xml, value-processor/src/org/immutables/value/processor/Immutables.generator
The commit message explains the rationale:
```
Since immutable objects are stateless and the invocation of methods on
immutable objects does not have observable side effects, one should generally
use the result of such invocations. A class-level `@CheckReturnValue`
annotation communicates this fact. Tools such as Error Prone can check for
adherence to this contract [1].
An exception to this rule are various methods defined on the nested Builder
class, as those methods return `this`. Those methods may thus be annotated
`@com.google.errorprone.annotations.CanIgnoreReturnValue`.
This change only applies `@CheckReturnValue` if _both_ `@CheckReturnValue` and
`@CanIgnoreReturnValue` are on the classpath, for application of the former
without the latter needlessly forces users of the nested …
```
=> Add support for `@javax.annotation.CheckReturnValue`

value-fixture/src/org/immutables/fixture/deep/Canvas.java, value-fixture/test/org/immutables/fixture/deep/DeepImmutablesDetectionTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
Fix for #333.
In situations like this:
```
@Value.Style(deepImmutablesDetection = true)
@Value.Modifiable
public interface Foo {
List<Bar> getBars();
// ...
}
@Value.Modifiable
public interface Bar {
// ...
}
```
When the following methods are called:
`ImmutableFoo.Builder#bars(Iterable<Bar>)`,
`ImmutableFoo.Builder#addBar(Bar)`,
`ImmutableFoo.Builder#addBar(Bar ...)`,
`ImmutableFoo.Builder#addAllBar(Iterable<Bar>)`,
`ImmutableFoo.Builder#from(Foo)`
then the Bar parameters will be converted with ImmutableBar.copyOf
before being added to the list. This is more consistent with
non-collection @Value fields when deepImmutablesDetection is on, and
prevents cases where you have an ImmutableFoo with ModifiableBars
inside.
=> Call copyOf on add methods if deepImmutablesDetection is enabled

value-processor/src/org/immutables/value/processor/Immutables.generator
This is a draft PR following our discussion in #464. Open questions:
- In `Immutables.generator` there's a call to the `declareFields` template in `Renderers.generator`. For some reason I couldn't reference `a.containingType.generateJacksonProperties` for the attributes passed in there. (It says `org.immutables.value.processor.encode.Type.generateJacksonProperties` is unresolvable, which is true.) Do you know how to get that to work (and whether it's important)?
- Did I miss any (other) fields?
=> When generating `@JsonProperty`s, mark fields `@JsonIgnore`d

value/src/org/immutables/value/Value.java
@elucash it occured to me that instead of smart ass-ing _("sic!")_ in https://github.com/immutables/immutables/issues/471 re. deepImmutablesDetection's JavaDoc I could just make a minor contribution to fix it up.. ;-)
=> Fix minor spelling issues in deepImmutablesDetection() JavaDoc

value-fixture/test/org/immutables/fixture/deep/DeepImmutablesDetectionTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
Like #333 but for Modifiables instead of Immutables...
In situations like this:
@Value.Style(deepImmutablesDetection = true)
@Value.Modifiable
public interface Foo {
List<Bar> getBars();
// ...
}
@Value.Modifiable
public interface Bar {
// ...
}
When the following methods are called:
ModifiableFoo#setBars(Iterable<Bar>),
ModifiableFoo#addBar(Bar),
ModifiableFoo#addBar(Bar ...),
ModifiableFoo#addAllBar(Iterable<Bar>)
ModifiableFoo#from(Foo)
then the Bar parameters will be converted with
ModifiablePoint.create().from()
before being added to the list if they are not already ModifiablePoints.
This is more consistent with non-collection @Value fields when
deepImmutablesDetection is on, and prevents cases where you have an
ModifiableFoo with ImmutableBars …
=> Call Modifiable factory on elements in add methods if deepImmutablesDetection is enabled

value-fixture/src/org/immutables/fixture/OrderAttributeValue.java, value-fixture/test/org/immutables/fixture/ValuesTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/AttributeTypeKind.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
From the commit message:
```
While there, also:
- Tweak the error messages in `ValueAttribute#checkOrderAnnotations`. (Note
that `NavigableSet` extends `SortedSet` and `NavigableMap` extends
`SortedMap`, so those don't need to be listed explicitly.)
- Fix the (unused) `AttributeTypeKind#isListMultimap`.
```
This PR relates to #516. Note that:
1. I added some tests and also tried the changes with `ImmutableSortedMultiset` in a local project and things seem to work, but I'm not sure I covered all cases.
2. I can trigger the error for when one specifies both `@NaturalOrder` and `@ReverseOrder`, but when I annotate an `ImmutableList` with (just) `@NaturalOrder`, the associated error is not triggered (as I also mentioned in #516). No idea why this is.
=> Support @{Natural,Reverse}Order on SortedMultiset

value-fixture/src/org/immutables/fixture/ordered/SortedMultisetWrapper.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
From the commit message:
```
Relax the check for `@NaturalOrder` and `@ReverseOrder` to allow unresolved
element/key types, as it is not possible to determine with certainty whether
such types are in fact `Comparable`.
```
This is a possible fix for #525. I replaced `#isComparableKey()` with `#isMaybeComparableKey()` because it was used nowhere else. If you prefer I can also retain the original method alongside the new method, or split the logic into a method `#isUnresolvedKey()`. Let me know :)
=> Allow unresolved ordered collection elements

value-fixture/src/org/immutables/fixture/ordered/SortedCollectionWrapper.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java
While reviewing PR #526 once more I noticed that I forgot to rename the test class. So this PR rectifies that and throws in two more tweaks:
1. Rename `SortedMultisetWrapper` -> `SortedCollectionWrapper` to match its content.
2. Deduplicate logic in `ValueAttribute#checkOrderAnnotations`.
3. Fix typo: "a map's key are Comparable" -> "a map's keys are Comparable".
=> Assorted fixes

value-fixture/src/org/immutables/fixture/modifiable/Companion.java, value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
Should fix a NPE when creating a modifiable model from an immutable one if a nullable List is actually null.
=> #578 Modifiable#addAll* misses null check on @Nullable

value-fixture/src/org/immutables/fixture/with/ForEquals.java, value-processor/src/org/immutables/value/processor/Immutables.generator
In a1d3518d4851291103fd98a449fbbd8fded90579 triggering `NumericEquality`
warnings is prevented for optional numbers. This change tackles non-optional
`java.lang.Number` instances.
This relates to #570.
=> Prevent Error-Prone `NumericEquality` warning

value-fixture/src/org/immutables/fixture/with/ForEquals.java, value-processor/src/org/immutables/value/processor/Immutables.generator
Summary of changes:
- Fix typo in `org.immutables.fixture.with.ForEquals`.
- Compare enums by reference.
(Looking again at the code derived from `ForEquals`, only the equality check mentioned in https://github.com/immutables/immutables/pull/583#issuecomment-287989754 is changed, as desired.)
=> Followup of #583

gson/src/org/immutables/gson/stream/JsonParserReader.java, mongo/test/org/immutables/mongo/fixture/BasicMongoOperationsTest.java, mongo/test/org/immutables/mongo/fixture/MongoContext.java, mongo/test/org/immutables/mongo/fixture/holder/Holder.java, mongo/test/org/immutables/mongo/fixture/holder/HolderJsonSerializer.java, mongo/test/org/immutables/mongo/fixture/holder/HolderTest.java, mongo/test/org/immutables/mongo/fixture/holder/Primitives.java
In some cases mongo repository classes couldn't load data due to the following error:
```
Expected VALUE_STRING but was VALUE_NUMBER_FLOAT
```
GSON lazily loads numbers (to avoid parsing costs) so number may remain string from JsonParserReader perspective.
=> fixed bug for polymorphic classes with primitives inside

gson/pom.xml, metainf/pom.xml, pom.xml
The metainf project produces a standalone jar, but the pom file still
declares the shaded dependencies which defeats the purpose of creating a
shaded standalone jar.
By aligning the metainf pom file with the value pom file a proper
standalone jar is created for the metainf processor. This removes the
standalone classifier and creates a standalone jar by default.
=> Create proper standalone jar for metainf processor

mongo/src/org/immutables/mongo/Mongo.java, mongo/src/org/immutables/mongo/repository/Repositories.java, mongo/test/org/immutables/mongo/fixture/flags/FlagsTest.java, mongo/test/org/immutables/mongo/fixture/flags/Repo.java, mongo/test/org/immutables/mongo/fixture/flags/package-info.java, value-processor/src/org/immutables/value/processor/Repositories.generator, value-processor/src/org/immutables/value/processor/meta/ValueType.java
Added two `@Mongo.Repository` annotation attributes:
1. `readonly`. Setting this flag to `true` will remove `delete` / `insert` / `upsert` / `andModifyFirst` ...  write operations from repository. The default value is `false`
2. `index`. Setting this flag to `false` will disable indexer functionality of the repository.
=> added (eg. readonly) flags to customize repository generator

value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/ValueType.java
If the type suppresses either all or unchecked, it is unnecessary to
also suppress that warning on a method on the type.
The Buck project compiles with ecj with
org.eclipse.jdt.core.compiler.problem.unusedWarningToken=error where
this is flagged as an error.
=> Don't generate duplicate @SuppressWarnings

mongo/src/org/immutables/mongo/repository/internal/Support.java
If you use LocalDateTime as a property: 
`
@Repository
public interface Foo {
LocalDateTime bar();
}
`
.. the generated FooRepository code will not compile.
=> mongo support for subtyped comparable like LocalDateTime

value-processor/src/org/immutables/value/processor/meta/Round.java
Because `HashSet` iteration order can vary from run to run, the order in which the processor
was generating nested value classes could change from run to run. This caused problems with
build systems like Buck that assume deterministic output so that artifacts can be cached.
Switching to a `LinkedHashSet` takes care of the issue.
=> Fix nondeterminism in code generation of nested values

value-processor/src/org/immutables/value/processor/Immutables.generator
- Add `@SafeVarargs` in more relevant places.
- Where `@SafeVarargs` is used, also add `@SuppressWarnings("varargs")`.
The suppression is not necessary in all cases, but avoids the issue described
in #392, making Immutables more friendly towards users compiling with
`-Xlint:all` or `-Xlint:varargs`.
=> Extend safe varargs annotation usage

value-fixture/pom.xml
Rationale:
- Prevents regressions w.r.t. this feature.
- Proves that the issue reported in https://github.com/google/error-prone/issues/647#issuecomment-341664913 is either already fixed or not covered by current tests.
CC @bmhm.
=> Handle `CheckReturnValue` violations as errors

value/pom.xml
This allows org.immutables.value to be referenced from Java 9 module
descriptors.
Affects #713
=> Publish an Automatic-Module-Name

value-processor/src/org/immutables/value/processor/Immutables.generator
see http://errorprone.info/bugpattern/MethodCanBeStatic
Fixes #717 https://github.com/immutables/immutables/issues/717
Signed-off-by: Michael Vorburger <vorburger@redhat.com>
=> Make checkNotIsSet() static for error-prone's MethodCanBeStatic

value-fixture/pom.xml, value-fixture/test/org/immutables/fixture/builder/AttributeBuilderTest.java, value-fixture/test/org/immutables/fixture/jackson/FieldConflictTest.java, value-fixture/test/org/immutables/fixture/jdkonly/JdkOptionalTest.java, value-fixture/test/org/immutables/fixture/marshal/MarshallingTest.java, value-fixture/test/org/immutables/fixture/serial/SerialTest.java, value-fixture/test/org/immutables/metainf/fixture/ServiceTest.java, value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Modifiables.generator
Where feasible, mark generated methods `static`. Where infeasible, add a suppression. The Gson code's complexity is such that I had to add an unconditional suppression at the top of the generated class.
@elucash, this change requires quite careful review, unfortunately. The compiler caught most issues, but if a fixture with a certain combination of features is absent, I might have missed an edge case.
Aside from appeasing Error Prone users, I think this change is worthwhile because use of `static` may allow micro-optimizations by the JVM, and we do want our Immutables to have efficient implementations. That said, whether the extra complexity introduced here is worth it is up for debate. WDYT?
Fixes #717. CC @vorburger.
=> Handle Error Prone's `MethodCanBeStatic` check

mongo/pom.xml, mongo/src/org/immutables/mongo/repository/Repositories.java, mongo/test/org/immutables/mongo/fixture/MongoCursorIsClosedTest.java
use `try / catch` block when fetching results from MongoCollection. Otherwise resources are not properly closed.
=> close MongoCursor after fetch

mongo/test/org/immutables/mongo/fixture/SimpleInserterTest.java
Added ```fail()``` where it should have been enforced
=> added forced failure if there is no DuplicateKeyException for unit tests

mongo/src/org/immutables/mongo/repository/internal/BsonWriter.java, mongo/test/org/immutables/mongo/fixture/NumbersTest.java, mongo/test/org/immutables/mongo/repository/internal/BsonDecimal128Test.java, mongo/test/org/immutables/mongo/repository/internal/BsonNumbersTest.java, mongo/test/org/immutables/mongo/repository/internal/BsonReaderTest.java, mongo/test/org/immutables/mongo/repository/internal/BsonWriterTest.java, mongo/test/org/immutables/mongo/repository/internal/Jsons.java
Explicit `NumbersTest` to validate number wrappers like `BigDecimal`, `BigInteger`, `AtomicLong` etc.
Also added a separate statement for `Byte` (inside `BsonWriter`) which will persist Byte as int32 (in mongo) instead of [default double](https://github.com/asereda-gs/immutables/blob/449d63b4f9c71e430a699ec75cbd093c383c6cb5/mongo/src/org/immutables/mongo/repository/internal/BsonWriter.java#L190).
=> added more tests for numbers

value-processor/src/org/immutables/value/processor/Immutables.generator
This removes 3 out of 18 `-Xlint:rawtypes` warnings in `value-fixtures`. Not a lot, but we happen to have code that triggers this particular case.
=> Avoid raw types in some generated code

generator/src/org/immutables/generator/ExtensionLoader.java
When using org.immutables:builder:2.6.0
Eclipse Oxygen APT raises 
`org.immutables.value.internal.$processor$.$Processor threw java.lang.IllegalArgumentException: Unsupported location: CLASS_PATH
at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getFileFromOutputLocation(IdeFilerImpl.java:186)
at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getResource(IdeFilerImpl.java:154)
at org.immutables.value.internal.$generator$.$ExtensionLoader.getClasspathResourceText($ExtensionLoader.java:78)
at org.immutables.value.internal.$generator$.$ExtensionLoader.access$000($ExtensionLoader.java:33)
at org.immutables.value.internal.$generator$.$ExtensionLoader$1.get($ExtensionLoader.java:50)
at org.immutables.value.internal.$generator$.$ExtensionLoader$1.get($ExtensionLoad …
=> Resolve Eclipse APT Unsupported location: CLASS_PATH

value-processor/src/org/immutables/value/processor/Immutables.generator
Version 2.6.3 generates this Javadoc:
```
...
@return A lazily initialized value of the {@code l.name} attribute
...
```
=> Fix Javadoc generated for @Value.Lazy

value-fixture/src/org/immutables/fixture/strict/Aar.java, value-processor/src/org/immutables/value/processor/Immutables.generator
This resolves some instances of Error Prone's [`FieldCanBeFinal`](http://errorprone.info/bugpattern/FieldCanBeFinal) bug pattern. I started working on this before I realized that I should just wait for #792 to be resolved, as the problem will then "go away" in combination with `-XepDisableWarningsInGeneratedCode`. Opening this PR in case you're interested in this contribution regardless.
=> Make builder fields final when possible

value-fixture/src/org/immutables/fixture/modifiable/GenericHolder.java, value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/Immutables.java, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/meta/ValueType.java
Currently the Modifiable implementations check if a field has been set and throw if not, which prevents a partial Modifiable object seeding a new builder.
This PR adds a Builder and Modifiable `from` overload for the Modifiable type, as well as a dynamic `instanceof` check since we can't rely on people statically calling the overload.  The overload then checks `isSet` on mandatory attributes before attempting to copy them, avoiding the exception.
=> Improve `from` behavior for mandatory fields on partial Modifiable instances

value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/builder/attribute_builders/ThirdPartyImmutableWithBuilderClassCopyMethod.java, value-fixture/src/org/immutables/fixture/builder/attribute_builders/ThirdPartyImmutableWithBuilderInstanceCopyMethod.java, value-fixture/src/org/immutables/fixture/builder/attribute_builders/ThirdPartyImmutableWithValueClassCopyMethod.java, value-fixture/src/org/immutables/fixture/builder/detection/NewTokenAttributeBuilderParent.java, value-fixture/src/org/immutables/fixture/builder/detection/NoNewTokenAttributeBuilderParent.java, value-fixture/src/org/immutables/fixture/builder/functional/AttributeBuilderBuilderI.java, value-processor/src/org/immutables/value/processor/meta/AttributeBuilderReflection.java, value-processor/src/org/immutables/value/processor/meta/Styles.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java
The discovery mechanism needs to be more strict for protocol buffers
because there are several methods which have the right signature, but
are not part of the builder API.
First, we make sure all methods for an attribute builder match the
specified Value#attributeBuilder patterns
Second, we ensure that the return methods are equivalent using
typeMirriors#isSameType. Using equals was working intermittently, and
the documentation on equals says to use the isSameType instead.
=> Support protocol buffer attributes

mongo/pom.xml, mongo/src/org/immutables/mongo/Wrapper.java, mongo/src/org/immutables/mongo/bson4gson/BsonReader.java, mongo/src/org/immutables/mongo/bson4gson/BsonWriter.java, mongo/src/org/immutables/mongo/bson4gson/GsonCodecs.java, mongo/src/org/immutables/mongo/bson4jackson/BsonGenerator.java, mongo/src/org/immutables/mongo/bson4jackson/BsonParser.java, mongo/src/org/immutables/mongo/bson4jackson/JacksonCodecs.java, mongo/src/org/immutables/mongo/bson4jackson/package-info.java, mongo/src/org/immutables/mongo/repository/RepositorySetup.java, mongo/src/org/immutables/mongo/repository/internal/Constraints.java, mongo/test/org/immutables/mongo/bson4gson/GsonCodecsTest.java, mongo/test/org/immutables/mongo/bson4jackson/BsonParserTest.java, mongo/test/org/immutables/mongo/fixture/JacksonRepoTest.java
Add separate JsonParser (wrapper for [BsonReader](http://mongodb.github.io/mongo-java-driver/3.7/javadoc/org/bson/BsonReader.html)) and JsonGenerator (wrapper for [BsonWriter](http://mongodb.github.io/mongo-java-driver/3.7/javadoc/org/bson/BsonWriter.html)) which delegates streaming operations to mongo java driver.
Add custom CodecRegistry which instantiates Codec(s) based on existing ObjectMapper (serializers / deserializers). All jackson specific classes are located in `bson4jackson` package.
Move Gson classes into separate package (`bson4gson`).
This feature is currently considered experimental (@Beta).
Closes immutables/immutables#835
=> Support for Jackson serialization in Mongo Adapter.

value-processor/src/org/immutables/value/processor/Gsons.generator, value-processor/src/org/immutables/value/processor/Repositories.generator
I've found more nested classes that need to be annotated with `org.immutables.value.Generated`.
* `*.GsonAdapters*.*NamingFields`
* `*.GsonAdapters*.*TypeAdapter`
* `*.*Repository.Criteria`
* `*.*Repository.Finder`
* `*.*Repository.Modifier`
* `*.*Repository.Replacer`
* `*.*Repository.Serialization`
* `*.*Repository.*NamingFields`
It would be great to fix that because tools like JaCoCo interpreting it.
@elucash I'm hungry for a new release with these changes.
=> Add org.immutables.value.Generated annotation to nested classes #827

mongo/src/org/immutables/mongo/bson4jackson/BsonParser.java, mongo/test/org/immutables/mongo/fixture/JacksonRepoTest.java
When the ObjectMapper is configured with the module generated by `JacksonCodecs.module(MongoClient.getDefaultCodecRegistry())`, repositories successful serialize documents containing UUIDs. These are serialized using Mongo Java driver's default codec for UUIDs: BinData type 3.
However, they cannot be deserialized using Jackson without a custom deserializer. A custom `UUIDDeserializer` allows the UUID serialized by the Mongo-backed `JacksonCodec` to be deserialized, in theory.
In order for this to work though, the Immutable's BsonParser must be updated to gracefully handle BsonType.BINARY. The PR contains this change.
Here's an example `UUIDDeserializer`:
```java
/**
* Custom deserializer for UUID (stored as {@link BsonType#BINARY})
*/
public class UUIDDeserializer extends …
```
=> Fix Jackson BsonParser to support a UUID Deserializer

value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/SourceNames.java
Fixes #736.
Summary of our situation and how I came to this proposal: We have a small Maven module with a `com/company/package-info.java` file containing a company-wide `@Value.Style` configuration. Other Maven modules declare `@Value.Immutable` types in `com/company/foo/bar/baz` packages. With JDK 8 this works fine; with JDK 9-11 it works only after applying this patch. My understanding of  the problem is that with JDK 9+, Immutables only finds `com/company/foo/bar` as a parent of `com/company/foo/bar/baz` if the former contains a `package-info.java` file. The patch proposed here doesn't bail out when the parent is not found, but instead keeps traversing to the root, since packages higher up _may_ contain a `package-info.java` file.
@elucash I tested this change on a private project …
=> Fix parent package traversal in JDK 9+

generator-processor/src/org/immutables/generator/processor/Trees.java, generator/src/org/immutables/generator/Output.java, generator/src/org/immutables/generator/Templates.java, trees/test/org/immutables/trees/ast/SampleNodes.java, value-fixture/test/org/immutables/fixture/marshal/MarshallingTest.java, value-fixture/test/org/immutables/fixture/nested/NestedValuesTest.java, value-processor/src/org/immutables/value/processor/encode/Code.java
Guava 26 removed the static constants being used by Immutables, which can make
it very difficult to use Immutables in a project with a newer Guava version.
Version 19 (which happily is already in use here) provided static methods to
replace the constants, so switch to using them.
=> Use Guava static methods for better forward compatibilty.

criteria/README.md, criteria/pom.xml, criteria/src/org/immutables/criteria/Criteria.java, criteria/src/org/immutables/criteria/Disjunction.java, criteria/src/org/immutables/criteria/DocumentCriteria.java, criteria/src/org/immutables/criteria/ValueCriteria.java, criteria/src/org/immutables/criteria/constraints/BooleanCriteria.java, criteria/src/org/immutables/criteria/constraints/ComparableCriteria.java, criteria/src/org/immutables/criteria/constraints/Constraints.java, criteria/src/org/immutables/criteria/constraints/CriteriaCreator.java, criteria/src/org/immutables/criteria/constraints/ObjectCriteria.java, criteria/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/src/org/immutables/criteria/constraints/ReflectionEvaluator.java, criteria/src/org/immutables/criteria/constraints/StringCriteria.java, criteria/test/org/immutables/criteria/fixture/Person.java, criteria/test/org/immutables/criteria/fixture/ReflectionTest.java, pom.xml, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/Criteria.java, value-processor/src/org/immutables/value/processor/Processor.java, value-processor/src/org/immutables/value/processor/Repositories.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaMirrors.java, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java
First draft of Criteria API. Please don't merge it yet.
Generate criteria class based on existing model and evaluate it using visitor pattern.
Right now only reflection based evaluator is provided. 
1. (sub-)Criteria on Iterables. Example 
```java
user.friends.anyMatch(FriendCriteria.create().age().greaterThan(22));
user.friends.noneMatch(FriendCriteria.create().age().greaterThan(22))
user.friends.allMatch(FriendCriteria.create().age().greaterThan(22));
// something similar for optionals
```
2. Combining criterias (using `AND`s / `OR`s)
3. Nested criterias
4. Projections
5. Aggregations
5. Comparison between fields: `field1 = field2` 
6. DSL is not restrictive enough.
```java
// one can write something like this
criteria.or().or().or();
criteria.age().greaterThan(111).or().or(); // or …
```
=> Stand-alone Criteria API to query different data-sources (initial draft)

value-processor/src/org/immutables/value/processor/meta/FromSupertypesModel.java
if a class defines a method with the same name as a "getter" method but with parameters, and that method is declared before the getter, it will be used to compare the return type against the getter method defined in the parent class, if they don't match, the attribute will be ignored from the "from" builder.
although it's probably not a common use case to have methods with parameters named like a getter, only methods without parameters should be considered anyway. 
I couldn't find unit tests for this, so didn't edit any, but happy to add test cases if there are tests for this in another module.
=> ignore methods with parameters when comparing with super type

criteria/common/README.md, criteria/common/src/org/immutables/criteria/DocumentCriteria.java, value-processor/src/org/immutables/value/processor/Criteria.generator
This is mainly done to minimize logic inside generated code
=> Push expression visitor implementation to upper class (as default interface method)

mongo/pom.xml, mongo/test/org/immutables/mongo/fixture/JacksonRepoTest.java, mongo/test/org/immutables/mongo/fixture/MongoAsserts.java, mongo/test/org/immutables/mongo/fixture/MongoContext.java, mongo/test/org/immutables/mongo/fixture/flags/FlagsTest.java
Traditionally we have used [Fongo](https://github.com/fakemongo/fongo) as our fake mongo server. Unfortunately,
development on that project has staled and it is not compatible with latest mongo driver versions (3.6+).
[Mongo Java Server](https://github.com/bwaldvogel/mongo-java-server) is more active and passed all integration tests.
Closes #929
=> Mongo Adapter. Replace Fongo by Mongo Java Server (embedded mongo for tests)

value-processor/src/org/immutables/value/processor/Repositories.generator
Since migration to [mongo codecs](http://mongodb.github.io/mongo-java-driver/3.10/bson/codecs/) a case of polymorphic serialization was missed (gson serialization). This seems to be an edge case and it is safer to fail fast during repository code generation until a proper solution is in place.
For more information see #934
=> Explicitly fail for repositories with Gson polymorphic mapping (@ExpectedSubtypes)

mongo/pom.xml, mongo/test/org/immutables/mongo/fixture/MongoAsserts.java
New version of the librabry fixes the issue with `codeName=DuplicateKey` for duplicate keys.
Different value was returned before which was inconsistent with real mongo DB.
=> Upgrade mongo java server to 1.14.0

criteria/common/src/org/immutables/criteria/DocumentCriteria.java, criteria/common/src/org/immutables/criteria/constraints/BooleanCriteria.java, criteria/common/src/org/immutables/criteria/constraints/Call.java, criteria/common/src/org/immutables/criteria/constraints/ComparableCriteria.java, criteria/common/src/org/immutables/criteria/constraints/CriteriaCreator.java, criteria/common/src/org/immutables/criteria/constraints/DebugExpressionVisitor.java, criteria/common/src/org/immutables/criteria/constraints/DnfExpression.java, criteria/common/src/org/immutables/criteria/constraints/EmptyExpression.java, criteria/common/src/org/immutables/criteria/constraints/Expressions.java, criteria/common/src/org/immutables/criteria/constraints/Literal.java, criteria/common/src/org/immutables/criteria/constraints/ObjectCriteria.java, criteria/common/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/common/src/org/immutables/criteria/constraints/StringCriteria.java, criteria/common/test/org/immutables/criteria/Person.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Introduce `DnfExpression` which keeps track of conjuction / disjunction (`AND / OR`) as separate lists.
This gives a shallow expression tree.
=> Use Disjunctive Normal Form (DNF) with criteria (allows chaining of expressions).

criteria/common/src/org/immutables/criteria/InMemoryExpressionEvaluator.java, criteria/common/test/org/immutables/criteria/Person.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java
It was deleted previously since Expression API wasn't stable.
Can be used to validate API and perform some basic testing.
Probably this can be moved to a separate module similar to `mongo` / `elasticsearch`
=> Resurrect in memory expression evaluator

criteria/common/src/org/immutables/criteria/constraints/OptionalCriteria.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Optional criterias can be "unwrapped" into element specific criteria(s) (eg. string)
```
Optional<String> lastName;
lastName.value().startsWith("J")
```
=> Apply criteria on Optional attributes

criteria/common/src/org/immutables/criteria/InMemoryExpressionEvaluator.java, criteria/common/src/org/immutables/criteria/constraints/DebugExpressionVisitor.java, criteria/common/src/org/immutables/criteria/constraints/DnfExpression.java, criteria/common/src/org/immutables/criteria/constraints/Expression.java, criteria/common/src/org/immutables/criteria/constraints/ExpressionVisitor.java, criteria/common/src/org/immutables/criteria/constraints/Expressions.java, criteria/common/src/org/immutables/criteria/constraints/NilExpression.java, criteria/common/test/org/immutables/criteria/ReflectionTest.java
In future it may be useful to expose some context during expression evaluation.
=> Add context (payload) to expression visitor

mongo/src/org/immutables/mongo/repository/Repositories.java, value-processor/src/org/immutables/value/processor/Repositories.generator
We have use cases in which we want to aggregate documents of generated repositories. Since the generator does not provide an API to build an Aggregation Pipeline, we write them by hand. In this case, we want to extend the generated repository with custom functionality where we need access to the used MongoCollection.
=> Make generated MongoDB repositories extensible

mongo/test/org/immutables/mongo/fixture/criteria/PersonCriteriaTest.java, value-processor/src/org/immutables/value/processor/Repositories.generator
I want to use the BSON representation of a `Criteria` instance in my custom extension of a generated repository.
For example, when I want to build a custom count method in my extended repository I do this:
```Java
@Immutable
@Repository
abstract class MyDoc {
abstract String name();
}
class MyDocExtendedRepository extends MyDocRepository {
MyDocExtendedRepository(RepositorySetup configuration) {
super(configuration);
}
long count(String prefix) {
Criteria criteria = criteria().nameStartsWith(prefix);
return collection().countDocuments(criteria.toBson());
}
}
```
=> Make BSON representation of a criteria available

criteria/common/pom.xml, criteria/mongo/README.md, criteria/mongo/pom.xml, criteria/mongo/src/org/immutables/criteria/mongo/MongoRepository.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoVisitor.java, criteria/mongo/src/org/immutables/criteria/mongo/Mongos.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java, pom.xml
Add Mongo Adapter to see how criteria works with external data-sources. 
This implementation uses [reactive streams](https://github.com/mongodb/mongo-java-driver-reactivestreams) driver.
Add rxjava2 as test dependency for easier validation of results (which are async by default).
=> Criteria. First Sketches of Mongo Adapter

criteria/common/src/org/immutables/criteria/expression/Operators.java, criteria/common/src/org/immutables/criteria/matcher/BooleanMatcher.java, criteria/common/src/org/immutables/criteria/matcher/CollectionMatcher.java, criteria/common/src/org/immutables/criteria/matcher/ComparableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaContext.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaCreator.java, criteria/common/src/org/immutables/criteria/matcher/Matchers.java, criteria/common/src/org/immutables/criteria/matcher/ObjectMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalMatcher.java, criteria/common/src/org/immutables/criteria/matcher/StringMatcher.java, criteria/common/test/org/immutables/criteria/PersonTest.java, criteria/common/test/org/immutables/criteria/TypeHolderTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator
Matchers are not implemented as interfaces with default methods.
=> Criteria. Migrate matchers to interfaces

criteria/common/src/org/immutables/criteria/Repository.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchRepository.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticsearchIntegrationTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/QueryBuildersTest.java, criteria/geode/src/org/immutables/criteria/geode/GeodeRepository.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoQueryVisitor.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoRepository.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoRepositoryTest.java
Currently used as a placeholder for future features like skip / offset / sort etc.
=> Criteria. Introduce Finder interface inside Repository

criteria/common/src/org/immutables/criteria/expression/Root.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/src/org/immutables/criteria/geode/Geodes.java, criteria/geode/test/org/immutables/criteria/geode/GeodeIntegrationTest.java
It is currently checking for existence of a predicate.
For empty (missing) predicate `map.clear()` is called.
=> Limited support of delete operation in Geode

criteria/common/src/org/immutables/criteria/adapter/InternalReader.java, criteria/common/src/org/immutables/criteria/adapter/InternalWatcher.java, criteria/common/src/org/immutables/criteria/adapter/Operations.java, criteria/common/src/org/immutables/criteria/expression/Query.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchBackend.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticsearchIntegrationTest.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/src/org/immutables/criteria/geode/Geodes.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoBackend.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
Rename Operations.Query to Operations.Select to avoid confusion with Query
In backend most of method are using Query instead of DocumentCriteria (which is
reserved for front-end)
Remove unused transform() method.
Remove entity class dependency in ElasticsearchBackend constructor
=> Move limit / offset attributes from Operations.Query to Query class

criteria/mongo/src/org/immutables/criteria/mongo/bson4jackson/IdAnnotationModule.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoIntegrationTest.java
Avoid declaring redundant `@JsonProperty` annotations when `@Criteria.Id` is already present
=> Introduce jackson IdAnnotationModule which maps @Criteria.Id to _id mongo field

criteria/common/test/org/immutables/criteria/personmodel/Person.java, criteria/geode/pom.xml, criteria/geode/src/org/immutables/criteria/geode/CqDisposable.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/geode/src/org/immutables/criteria/geode/GeodeEventListener.java, criteria/geode/test/org/immutables/criteria/geode/GeodeCqTest.java
Implement Operation.Watch for Geode adapter using native
[Continuous Query](https://geode.apache.org/docs/geode-native/18/continuous-queries.html)
=> Support for Geode Watcher (CQ / Continuous Query)

value-processor/src/org/immutables/value/processor/Criteria.generator
Hide unnecessary information from IDE
=> Make CriteriaContext private field inside generated Criteria class

criteria/elasticsearch/pom.xml, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchBackend.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchOps.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/Scrolling.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ScrollingTest.java, pom.xml
Have some tests which validate scrolling with small sizes (1, 2, 3 etc.)
=> Add scroll support to Elasticsearch backend

criteria/common/src/org/immutables/criteria/expression/Expressions.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/inmemory/src/org.immutables.criteria.inmemory/InMemoryExpressionEvaluator.java, criteria/mongo/src/org/immutables/criteria/mongo/MongoQueryVisitor.java
InMemoryOperator had missing handling of NOT.
For Mongo, things were more intricate. $not has specific logic and can't be applied on all levels
(like in boolean algebra). Sometimes ot has to be replaced with $nor. or $eq -> $ne etc.
=> Better support for NOT operator in different backends

value-processor/pom.xml, value-processor/test/org/immutables/value/processor/meta/ProcessorRule.java, value-processor/test/org/immutables/value/processor/meta/ProcessorRuleTest.java
Intended for unit test
Allows a more fine-grained testing of ValueType / ValueAttribute and associated classes
=> Create ProcessorRule (JUnit4 rule) to test immutables annotation processor

criteria/common/src/org/immutables/criteria/matcher/IterableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalMatcher.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/test/org/immutables/value/processor/meta/CriteriaModelTest.java
Allows more complex logic to be encoded in java.
Add unit tests to validate matchers (before java files are created)
=> Move Matcher creation logic from template into java class (CriteriaModel)

criteria/common/src/org/immutables/criteria/matcher/BooleanMatcher.java, criteria/common/src/org/immutables/criteria/matcher/ComparableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaContext.java, criteria/common/src/org/immutables/criteria/matcher/Matchers.java, criteria/common/src/org/immutables/criteria/matcher/ObjectMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalMatcher.java, criteria/common/src/org/immutables/criteria/matcher/StringMatcher.java, criteria/common/src/org/immutables/criteria/matcher/WithMatcher.java, criteria/common/test/org/immutables/criteria/ExpressionAsStringTest.java, criteria/common/test/org/immutables/criteria/TypeHolderTest.java, criteria/common/test/org/immutables/criteria/nested/NestedTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/EmbeddedElasticsearchResource.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryExpressionEvaluatorTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java, value-processor/test/org/immutables/value/processor/meta/CriteriaModelTest.java
`with()` and `not()` can now be used on String / Comparable / Object etc.
Remove `OptionalMatcher.value(...)` which is somewhat redundant (`with()`
is more generic and applicable on all matchers)
Criteria fields are not longer generated. Using StringMatcher.Template
=> Introduce WithMatcher on all levels: scalar and object/model

.travis.yml
Travis build with oraclejdk8 fails due to LTS ?
=> Use openjdk8 (previously oraclejdk8) for Travis CI

criteria/common/src/org/immutables/criteria/Criteria.java, criteria/common/src/org/immutables/criteria/adapter/Backends.java, criteria/common/src/org/immutables/criteria/adapter/Operations.java, criteria/common/src/org/immutables/criteria/repository/reactive/ReactiveWritable.java, criteria/elasticsearch/src/org/immutables/criteria/elasticsearch/ElasticsearchBackend.java, criteria/geode/src/org/immutables/criteria/geode/GeodeBackend.java, criteria/inmemory/src/org.immutables.criteria.inmemory/InMemoryBackend.java, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator
Simplify repository logic and allow single operation insert().
Support for `put(key, value)` is on hold since ID (key) can be extracted from `value`.
=> Remove Operations.KeyedInsert and extract object ID (in backend)  using reflection

criteria/common/test/org/immutables/criteria/ExpressionAsStringTest.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/common/test/org/immutables/criteria/personmodel/PersonTest.java, criteria/common/test/org/immutables/criteria/processor/CriteriaModelProcessorTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticModelTest.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryExpressionEvaluatorTest.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java
Allows nicer source code when dynamically building criterias.
```java
// BEFORE
PersonCriteria<PersonCriteria.Self> crit = PersonCriteria.person;
// AFTER
PersonCriteria crit = PersonCriteria.person;
```
=> Separate Criteria into 2 classes: (main) FooCriteria and FooCriteriaTemplate

criteria/common/src/org/immutables/criteria/matcher/OptionalBooleanMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalComparableMatcher.java, criteria/common/src/org/immutables/criteria/matcher/OptionalStringMatcher.java, criteria/common/src/org/immutables/criteria/matcher/PresentAbsentMatcher.java, criteria/common/test/org/immutables/criteria/TypeHolderTest.java, criteria/common/test/org/immutables/criteria/nested/NestedTest.java, criteria/common/test/org/immutables/criteria/processor/CriteriaModelProcessorTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticModelTest.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryExpressionEvaluatorTest.java, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java
Introduce three interfaces which combine functionality of Optional and target type matchers:
1. OptionalStringMatcher
2. OptionalBooleanMatcher
3. OptionalComparableMatcher
It is now possible to write `optionalBool.isTrue()` instead of `optionalBool.value().isTrue()`
=> Add Optional-like intersection types for String, Comparable and boolean

value-processor/src/org/immutables/value/processor/Repositories.generator
There is no reason to not allow the developer to initialize the `_id` field during upsert.
=> Enable _id initialization in MongoDB

value-fixture/src/org/immutables/fixture/generics/GenericCore.java, value-fixture/test/org/immutables/fixture/generics/GenericCoreTest.java, value-processor/src/org/immutables/value/processor/meta/FromSupertypesModel.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java
We use the [egg pattern](https://github.com/HubSpot/hubspot-immutables#egg-pattern) heavily at my company and this PR addresses an issue we've faced where `Builder.from()`'s are not generated for supertypes when all types have the same type parameter. To see what I mean, check out this test I added (https://github.com/immutables/immutables/compare/master...tpetr:generic-inherit?expand=1#diff-f5bc5bf0a9b538e82ec484267fceffdd) -- I need to be able to pass a `ImmutableGenericChild` to `ImmutableGenericAdult.Builder.from()`.
This PR adds support for direct supertypes where both classes have just one type parameter with matching bounds and names. I wasn't able to safely reason about anything more complicated than that 😓 
Let me know if this all makes sense or if there's anything I can do to …
=> add Builder.from() support for direct ancestors with just one type parameter

value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/LazyHash.java, value-fixture/src/org/immutables/fixture/annotation/LazyhashAnnotation.java, value-fixture/test/org/immutables/fixture/LazyHashTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/ValueImmutableInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java
Add `lazyhash` attribute to `@Value` annotation which generates additional private class field `hashCode`.
```java
// pseudo-code for lazy evaluation of hashcode
public int hashCode() {
int h = this.hashCode;
if (h == 0) {
// 0 is considered unset int
h = computeHashCode();
this.hashCode = h;
}
return h;
}
```
This pattern is called [racy-single-check](http://javaagile.blogspot.com/2013/05/the-racy-single-check-idiom.html). From Effective Java : 
> If you don't care whether every thread recalculates the value of a field, and the type of the field is a primitive other than long or double, then you may choose to remove the volatile modifier from the field declaration in the single-check idiom [calculating the value of a volatile field if it's null]. This variant is known as the racy …
=> Lazy computation of hashCode #857

criteria/common/test/org/immutables/criteria/processor/JavaBeanModelTest.java, criteria/common/test/org/immutables/criteria/repository/AsyncModel.java, value-processor/src/org/immutables/value/processor/Criteria.generator, value-processor/src/org/immutables/value/processor/CriteriaRepository.generator, value-processor/src/org/immutables/value/processor/Processor.java, value-processor/src/org/immutables/value/processor/meta/Constitution.java, value-processor/src/org/immutables/value/processor/meta/CriteriaModel.java, value-processor/src/org/immutables/value/processor/meta/JavaBeanAttributesCollector.java, value-processor/src/org/immutables/value/processor/meta/Proto.java, value-processor/src/org/immutables/value/processor/meta/Round.java, value-processor/src/org/immutables/value/processor/meta/Styles.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueTypeComposer.java
Generate criteria from JavaBean definition #1092
Add separate collector which scans for getters / setters is a non-abstract class (with @Criteria and @Criteria.Repository annotations).
Helpful for projects with non-immutables classes which still want to leverage criteria API.
```java
@Criteria // enable DSL generation on existing class
// generate CustomPojoCriteria
class CustomPojo {
private String foo;
String getFoo() {...}
void setFoo(String foo) {...}
}
```
=> Generate criteria from Pojo / JavaBean #1092

gson/pom.xml, gson/src/org/immutables/gson/stream/JsonGeneratorWriter.java, gson/src/org/immutables/gson/stream/JsonParserReader.java, gson/src/org/immutables/gson/stream/XmlParserReader.java, gson/test/org/immutables/gson/bridge/GsonJacksonBridgeSerializationTest.java, gson/test/org/immutables/gson/bridge/TestEnum.java, gson/test/org/immutables/gson/bridge/TestObject.java, gson/test/org/immutables/gson/bridge/TestSubObject.java
- Fixed issue where integers are always printed as doubles
- Fixed issue using the jackson XML streaming parser where boolean tokens are always strings
=> Isuues with Gson Jackson Bridge

criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/elasticsearch/test/org/immutables/criteria/elasticsearch/ElasticPersonTest.java, criteria/geode/src/org/immutables/criteria/geode/GeodeQueryVisitor.java, criteria/geode/test/org/immutables/criteria/geode/AutocreateRegion.java, criteria/geode/test/org/immutables/criteria/geode/GeodeIntegrationTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodePersonTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodePojoTest.java, criteria/geode/test/org/immutables/criteria/geode/GeodeQueryVisitorTest.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryPersonTest.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoPersonTest.java
Adds support to OQL generator for subset of String queries
Regex, length, and empty queries currently fail for Immutables but pass for a regular POJO; this likely indicates an issue with the PDX (De)Serialisation.
=> Support OQL String queries

value-processor/src/org/immutables/value/processor/Repositories.generator
This fixes issues to copy over set custom `@SuppressWarnings` annotations.
=> Fix suppress warnings for generated MongoDB repositories

value-annotations/src/org/immutables/value/Value.java, value-processor/src/org/immutables/value/processor/Modifiables.generator, value-processor/src/org/immutables/value/processor/meta/Constitution.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/Styles.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java
I was hoping for this feature, and saw several other people had been requesting it, so I decided to take a stab at it.
Turns the current class for the innerBuilder which is extended by Builder and Modifiable implementations.
Supports both classes and interfaces, and will complain if it's a class that does not extend the base Abstract one.
=> Add support for Modifiable to extend an inner class/interface

value-fixture/src/org/immutables/fixture/modifiable/WithModifiableInterface.java, value-fixture/src/org/immutables/fixture/modifiable/WithModifiableSuperclass.java, value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java, value-processor/src/org/immutables/value/processor/meta/Constitution.java
Here are a few simple unit tests illustrating the functionality included in the previous pull request (#1140).
I discover one issue which is fixed here -- all my original test classes had both Value.Immutable and Value.Modifiable annotations;  and this change would fail to kick in if Value.Immutable was set.  This has been corrected, as illustrated in one of the attached tests.
=> Unit tests for Modifiable to extend an inner class/interface

value-processor/src/org/immutables/value/processor/encode/Instantiator.java
Close #1170
Respect insertion order when iterating multiple encodings by using an ArrayListMultimap to store them.
=> Predictable encoding conflict resolution

criteria/geode/src/org/immutables/criteria/geode/GeodeQueryVisitor.java, criteria/geode/test/org/immutables/criteria/geode/GeodeQueryVisitorTest.java, criteria/geode/test/org/immutables/criteria/geode/OqlGeneratorTest.java
This was a small change so I took a crack at it. Below is the log evidence that toUpperCase and toLowerCase is now working in my example app:
```
Jun 17, 2020 2:37:58 AM org.immutables.criteria.geode.SyncSelect call
FINE: Querying Geode with oql=[SELECT * FROM /person WHERE name.toLowerCase() = $1]  with 1 variables [$1=garrett]
Jun 17, 2020 2:37:58 AM Main main
INFO: toLowerCase() number of results: 2
Jun 17, 2020 2:37:58 AM org.immutables.criteria.geode.SyncSelect call
FINE: Querying Geode with oql=[SELECT * FROM /person WHERE name.toUpperCase() = $1]  with 1 variables [$1=GARRETT]
Jun 17, 2020 2:37:58 AM Main main
INFO: toUpperCase() number of results: 2
Jun 17, 2020 2:37:58 AM org.immutables.criteria.geode.SyncSelect call
FINE: Querying Geode with oql=[SELECT * FROM /person WHERE name …
```
=> #1189: criteria-geode backend toLowerCase/toUpperCase add parentheses

value-processor/src/org/immutables/value/processor/Gsons.generator
When adding `@SuppressWarnings("rawtypes")` at method level _Eclipse_ will suppress all raw-types warnings inside that method. The warning `raw` is not supported by any IDE I would know of.
=> Fix SuppressWarnings

mongo/test/org/immutables/mongo/fixture/MongoContext.java, mongo/test/org/immutables/mongo/fixture/generic/GenericHolder.java, mongo/test/org/immutables/mongo/fixture/generic/GenericType.java, mongo/test/org/immutables/mongo/fixture/generic/GenericTypeJsonSerializer.java, mongo/test/org/immutables/mongo/fixture/generic/GenericTypeTest.java, value-processor/src/org/immutables/value/processor/Repositories.generator
Generating a Repository class for an immutable with a custom generic type field results in compilation errors ever since generated repositories were changed from using TypeAdapters to use MongoDB's Codec interface.  I understand that the recommended approach is to migrate to the Criteria API, however this will allow upgrading to the latest version of immutables that supports Criteria API and then perform a phased migration to Criteria API.
Below is the code generation before and after this pull request. The compilation errors are due to the initialization of this.valueEncoder and this.listOfValuesEncoder
BEFORE:
```
@Generated(from = "GenericHolder", generator = "Repositories")
private static class Serialization {
final Encoder<GenericType<?>> valueEncoder;
final Encoder<GenericType<?>> …
```
=> Fix repository generation for custom generic types

value-fixture/src/org/immutables/fixture/modifiable/BeanFriendly.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
When modifiable has modifiable default field, Immutables produces syntactically invalid code.
Same is true for derived and lazy.
BEFORE:
```
...
@Override
public final ModifiableMod getDefaultMod() {
return defaultModIsSet()
? defaultMod
: BeanFriendly.super.getDefaultMod(); // doesn't compile because return type of super getDefaultMod is not type of ModifiableMod
}
...
```
AFTER:
```
...
@Override
public final ModifiableMod getDefaultMod() {
if (defaultModIsSet()) {
return defaultMod;
} else {
BeanFriendly.Mod defaultMod = BeanFriendly.super.getDefaultMod();
return defaultMod instanceof ModifiableMod
? (ModifiableMod) defaultMod
: new ModifiableMod().from(defaultMod);
}
}
...
```
=> When modifiable has modifiable default field, Immutables produces syntactically invalid code.

value-fixture/src/org/immutables/fixture/nullable/NullablyElements.java, value-fixture/test/org/immutables/fixture/nullable/NullableAttributesTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
For boxed types generated code before this fix contains a loop like
```java
/**
* Adds elements to {@link T#getIds() ids} set.
* @param elements An iterable of ids elements
* @return {@code this} builder for use in a chained invocation
*/
@CanIgnoreReturnValue 
public final T.Builder addAllIds(Iterable<Long> elements) {
Objects.requireNonNull(elements, "ids element");
if (this.ids == null) {
this.ids = new ArrayList<Long>();
}
for (long element : elements) {
this.ids.add(Objects.requireNonNull(element, "ids element"));
}
return (T.Builder) this;
}
```
For invalid calls it is still NPE but static code analysis tools like https://github.com/google/error-prone may rightfully complain that requireNonNull is never needed due to iterating with unboxed type.
--For @SkipNulls case it is an NPE …
=> Fix addAll(Iterator<E>) NPE

value-fixture/src/org/immutables/fixture/with/WithEnums.java, value-fixture/test/org/immutables/fixture/with/WithEnumsTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
This PR removes redundant equality checks in `with...` methods on enum members (it was often checking for equality twice). For example:
_Given:_
```java
public abstract class WithEnums {
public abstract RoundingMode getRoundingMode();
@Nullable public abstract RoundingMode getNullableRoundingMode();
public abstract Optional<RoundingMode> getMaybeRoundingMode();
}
```
_Before: (Javadoc removed for brevity)_
```java
...
public final ImmutableWithEnums withRoundingMode(RoundingMode value) {
if (this.roundingMode == value) return this;
RoundingMode newValue = Objects.requireNonNull(value, "roundingMode");
if (this.roundingMode.equals(newValue)) return this;
return new ImmutableWithEnums(newValue, this.nullableRoundingMode, this.maybeRoundingMode);
}
public final …
```
=> Remove redundant equality checks in with... methods on enum members

generator/src/org/immutables/generator/AbstractGenerator.java, generator/src/org/immutables/generator/Output.java, generator/src/org/immutables/generator/StaticEnvironment.java
When generating with another annotation processor classes that will be processed by the _Immutables_ generators that also write files in `META-INF/services` the Java Compiler issues a warning like
`javax.annotation.processing.FilerException: Attempt to reopen a file for path /my/project/build/classes/java/main/META-INF/services/com.google.gson.TypeAdapterFactory`. To workaround this problem we should write these files when the annotation processing is over.
=> Write META-INF/services files when annotation processing is over

value-fixture/src/org/immutables/fixture/modifiable/BeanFriendly.java, value-fixture/test/org/immutables/fixture/modifiable/BeanFriendlyTest.java, value-processor/src/org/immutables/value/processor/Modifiables.generator
Modifiable's `from` method with bean friendly flag turned on returns void in the case where the modifiable class has 1 or more extended interfaces. 
This cause two issuers:
- it's inconsistent with from method that's generated for Modifiable that doesn't extend any extra interfaces
- it causes syntactic errors in Modifiable class in certain scenarios.
This change is focused on fixing these issues.
=> Bean friendly modifiable from method return converted result.

value-annotations/src/org/immutables/value/Value.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java
The idea is to avoid errors when logging immutable objects which carry a lot of data encoded as strings or type variables. This saves us from writing custom `toString` methods to avoid excessive logging when a lot of data gets transported with an immutable to be logged.
Please let me know what you think about it.
=> Truncate strings or values of type variables in `toString` method that are longer than a defined length

generator/src/org/immutables/generator/SourceOrdering.java
When upgrading immutables (2.7.3 -> 2.7.5), it fails with NPE in
SourceOrdering (line 260).
Unfortunately, I cannot reproduce the NPE with small example, but
at least I can add some diagnostics, so next time I will try to
upgrade, I will have some clue where to start looking.
Generally, when obtaining an item from a map by key, one should not
assume the value is not null.
=> Diagnostics for NPE in SourceOrdering

value-processor/src/org/immutables/value/processor/meta/SuppressedWarnings.java
Newer Java allows you to mark things as `@Deprecated(forRemoval=true)` which requires a separate warning to be suppressed.
For simplicity's sake, just always add it to the suppress list since it's not harmful if unused.
=> SuppressedWarnings: if it's deprecated, also suppress forRemoval

.github/workflows/ci.yml, generator/pom.xml, value-fixture/pom.xml, value-processor/src/org/immutables/value/processor/meta/Constitution.java
Added eclipse compiler to build matrix. It only affects value-fixture module compilation.
Some fixtures didn't work so I fixed them.
Some fixtures still didn't work and it was much harder to figure out the right fix for them. So i temporarily excluded them from the eclipse compilation.
I also removed so EOLed Java versions from the build matrix to speed things up.
=> Added eclipse compiler to build matrix

value-fixture/src/org/immutables/fixture/InternedClassWithSelfConstant.java, value-fixture/src/org/immutables/fixture/InternedInterfaceWithSelfConstant.java, value-fixture/test/org/immutables/fixture/InternedClassWithSelfConstantTest.java, value-fixture/test/org/immutables/fixture/InternedInterfaceWithSelfConstantTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
=> Support abstract classes declaring static interned instances of their own type

value-processor/src/org/immutables/value/processor/encode/EncodedElement.java, value-processor/src/org/immutables/value/processor/encode/Encodings.java, value-processor/src/org/immutables/value/processor/encode/Renderers.generator
Fixes https://github.com/immutables/immutables/issues/1307.
Method parameter annotations in Encodings are now stored in `Param#annotations()`, and the toString/parsing is adjusted to support this with the format `"@Foo @Bar param: Type"`. The Renderers generator is updated to add these annotations to the generated source.
I'm very new to the codebase, so please let me know if you have any suggestions.
=> Forward Encoding method parameter annotations

value-fixture/test/org/immutables/fixture/jackson/BugsTest.java, value-fixture/test/org/immutables/fixture/jackson/ObjectMappedTest.java, value-fixture/test/org/immutables/fixture/modifiable/ModifiablesTest.java
These were all detected with [NonDex](https://github.com/TestingResearchIllinois/NonDex); these fixes make the tests agnostic to the order of items in collections or entries in JSON objects.
=> Fix five flaky tests in value-fixture

annotate/src/org/immutables/annotate/InjectAnnotation.java
Restore missing parentheses eaten by the cookie monster.
=> [annotate] Fix javadoc typos

generator/pom.xml, value-fixture/pom.xml
Turns out we can include required module patches via manifest entry.
=> No explicit opens by using Add Opens manifest entry.

generator/pom.xml, value-fixture/pom.xml
Turns out Add-Opens never worked.
The reason it worked prior is that errorprone related opens are declared globally and therefore Immutables always had access to privileged compiler APIs.
This PR reinstates necessary flags back not to be deceived by what's going on.
=> Add Opens follow up.

testing/pom.xml
Hi! I found the pom file of project **_org.immutables:testing:2.9.1-SNAPSHOT_** introduced **_18_** dependencies. However, among them, **_2_** libraries (**_11%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
org.hamcrest:hamcrest-integration:jar:1.3:compile
org.apiguardian:apiguardian-api:jar:1.1.0:compile
---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency conflict issues (i.e., multiple versions of the same library). More importantly, one of the redundant dependencies **_org.apiguardian:apiguardian-api:jar:1.1.0:compile_** induced dependency conflict in the dependency graph. As such, I suggest a refactoring operation for **_org.immutables:testing:2.9.1-SNAPSHOT_**’s pom …
=> Could org.immutables:testing:2.9.1-SNAPSHOT drop off redundant dependencies?

value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/with/WithMapUnary.java, value-fixture/src/org/immutables/fixture/with/WithUnaryOperator.java, value-fixture/test/org/immutables/fixture/with/WithUnaryOperatorTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/Styles.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java, value-processor/src/org/immutables/value/processor/meta/ValueType.java
Implementation of #1408 using naming template as enabling style flag
=> #1408 withUnaryOperator style flag/naming template

mongo/pom.xml, mongo/src/org/immutables/mongo/bson4gson/GsonCodecs.java, mongo/src/org/immutables/mongo/repository/RepositorySetup.java, mongo/test/org/immutables/mongo/bson4gson/GsonCodecsTest.java, mongo/test/org/immutables/mongo/bson4gson/JavaTimeTest.java, mongo/test/org/immutables/mongo/fixture/GsonRepoTest.java
Avoid invalidating Gson type adapter cache when creating Mongo Repository.
We only register the delegatingTypeAdapterFactory if Gson does not have TypeAdapters registered for all Bson related types
=> Avoid invalidating Gson type adapter cache when creating Mongo Repository

value-fixture/src/org/immutables/fixture/jackson/StagedEntity.java, value-fixture/test/org/immutables/fixture/jackson/ObjectMappedTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
Fixing an issue with Jackson and staged builder feature interaction.
Essentially, null values are not allowed when the immutable entry is identified as not nullable.
=> fixing #1407 - Default value with explicit null should use default.

criteria/mongo/src/org/immutables/criteria/mongo/MongoSession.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoWriteResultTest.java
This PR fixes insert counters for the upsert operation described in https://github.com/immutables/immutables/issues/1376  Mongo doesn't provide it as `insertedCount`, but it could be get from the size of `upserts` collection
=> Fix counts in WriteResult for upsert operation

pom.xml
There are 1 security vulnerabilities found in org.apache.geode:geode-core 1.9.0
- [CVE-2019-10091](https://www.oscs1024.com/hd/CVE-2019-10091)
Upgrade org.apache.geode:geode-core from 1.9.0 to 1.15.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.geode:geode-core to 1.15.0

value-fixture/src/org/immutables/fixture/builder/ToBuilderMethod.java, value-processor/src/org/immutables/value/processor/Immutables.generator
This is meant to resolve #1459 as follows:
```diff
/**
* Creates a builder for {@link ImmutableToBuilderClassicWithGenerics ImmutableToBuilderClassicWithGenerics}.prefilled
* with attibute values of {@code this} instance to easily create modified copies.
* @return A new ImmutableToBuilderClassicWithGenerics builder with attributes of {@code this} instance
*/
-  public ImmutableToBuilderClassicWithGenerics.Builder<T><T> toBuilder()
+  public ImmutableToBuilderClassicWithGenerics.Builder<T> toBuilder() {
return ImmutableToBuilderClassicWithGenerics.<T>builder().from(this);
}
```
(snippet comes from `value-fixture/target/generated-sources/annotations/org/immutables/fixture/builder/ImmutableToBuilderClassicWithGenerics.java`)
=> Fix `toBuilder` generator with generics

value-processor/src/org/immutables/value/processor/Immutables.generator
* Uses the `new ArrayList(int)` constructor when `size` is available
* Fixes the initial capacity calculation considering the default load factor of `.75` for sets + maps
* Uses `ImmutableList.builderWithExpectedSize` where appropriate
This change avoids a bunch of "resize" operations and some unnecessary object allocations / heap pressure.
=> Populate correct initial capacity for List/Set/Map/ImmutableList.Builder

value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/style/MoreVisibleImplementationAsString.java, value-fixture/test/org/immutables/fixture/style/StyleTest.java, value-processor/src/org/immutables/value/processor/meta/Constitution.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java
In https://github.com/apache/iceberg/pull/8099 we would like to use a custom style annotation to modify the name of the generated enclosing class (mainly to keep API compatibility).
```
@Value.Enclosing
@Value.Style(typeImmutableEnclosing = "ImmutableSnapshotTable")
interface BaseSnapshotTable extends SnapshotTable {
interface Result extends SnapshotTable.Result {}
}
```
Now we'd also like to configure `visibility = Value.Style.ImplementationVisibility.PUBLIC` so that the generated class is publicly visible. 
However, doing that would mean that we'd be forcing a compile-time dependency to consumers due to the issue described in https://github.com/immutables/immutables/issues/291 and the currently suggested workaround for this is to have something like
``` …
```
=> Allow specifying visibility as string

value-fixture/src-java-11/org/immutables/fixture/module/ModuleIF.java, value-fixture/src-java-11/org/immutables/fixture/module/subpackage/HasModuleField.java, value-processor/src/org/immutables/value/processor/meta/TypeStringProvider.java
Because `java.lang` types get automatically imported, they can be "resolved" without being resolved to the same thing that they are in the source file. This ultimately winds up preventing the generated code from compiling.
I'd love any guidance you're willing to give around this / around testing this out. Thank you!
Closes #1475
=> Re-try to resolve types in java.lang

value-fixture/src/nonimmutables/YieldField.java, value-processor/src/org/immutables/value/processor/Immutables.generator
When using Immutables with Java versions supporting switch expressions (and the new `yield` keyword) and if one decides to define an immutable interface with say `getYield()` method:
```java
public interface SomeInterface {
int getYield();
}
```
the value processor generates an immutable class implementation which won't compile since the internal generated Builder class would have the following copying method:
```java
@CanIgnoreReturnValue 
public final Builder from(SomeInterface instance) {
Objects.requireNonNull(instance, "instance");
yield(instance.getYield()); <-- here the compiler will fail with 'Yield outside of switch expression'
return this;
}
```
It's enough to prepend the method call with `this.` and the compilation passes.
=> Fix 'yield outside of switch expression'

value-fixture/src/org/immutables/fixture/jdkonly/JdkColl.java, value-fixture/test/org/immutables/fixture/jdkonly/JdkOnlyTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
Tried to write some of our code to use the `@Value.NaturalOrder` annotation for comparable wrapped types and it failed. A simple fix was to use an upper bound wildcard in the generated code. Also added a testcase with an example.
=> Allows NaturalOrdering for Comparable type hierarchies

value-annotations/src/org/immutables/value/Value.java, value-fixture/src/org/immutables/fixture/jackson/JacksonNullable.java, value-fixture/test/org/immutables/fixture/jackson/JsonPropertyTest.java, value-processor/src/org/immutables/value/processor/meta/StyleInfo.java, value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java, value-processor/src/org/immutables/value/processor/meta/ValueMirrors.java
Hi,
Raising this PR to solve this issue raised a while back: https://github.com/immutables/immutables/issues/924.
Essentially when we generate a Value class, we are adding an 'JsonProperty' annotation, but this does not have the 'required=true' flag set for non-nullable fields.
This is useful when inspecting the classes for things like generating API specs and JSON Schemas.
I have set this to be controlled by a style flag, so users can disable this functionality if needed.
As seen in the docs (https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/latest/com/fasterxml/jackson/annotation/JsonProperty.html#required--), this should not actually affect deserialization behaviour for most users of Immutables, as they would be using the builder for deserialisation.
=> Added support for the 'required' attribute for the generated JSON Property Annotation

value-fixture/src/org/immutables/fixture/builder/ForLambdaBuilder.java, value-fixture/test/org/immutables/fixture/builder/AttributeBuilderTest.java, value-processor/src/org/immutables/value/processor/Immutables.generator
builder initializers with builder-init-lambda for attributes which types discovered to have builders.
only for the mode when style has `attributeBuilderDetection = true`
=> simple lambda builders

criteria/common/src/org/immutables/criteria/expression/Path.java, criteria/common/src/org/immutables/criteria/matcher/CriteriaContext.java, criteria/common/test/org/immutables/criteria/personmodel/AbstractPersonTest.java, criteria/common/test/org/immutables/criteria/personmodel/Toy.java, criteria/inmemory/src/org/immutables/criteria/inmemory/ExpressionInterpreter.java, criteria/inmemory/test/org/immutables/criteria/inmemory/InMemoryPersonTest.java, criteria/mongo/src/org/immutables/criteria/mongo/FindVisitor.java, criteria/mongo/test/org/immutables/criteria/mongo/MongoPersonTest.java
Criteria does not seem to support any() queries in sub-collections as described in the [documentation](https://immutables.github.io/criteria.html). 
Accordingly, the example
`person.pets.any().name.contains("fluffy"); // person has a pet which sounds like fluffy` 
from the documentation does not work out of the box and leads to exceptions. [asereda-gs](https://github.com/asereda-gs) confirms this in his [comment](https://github.com/immutables/immutables/issues/1457#issuecomment-1705632115) to the issue #1457.
This PR addresses this and adds support for any() queries for the InMemory and MongoDB backends and extends the AbstractPersonTest with corresponding tests.
=> Support Sub-Collection Queries for InMemory and MongoDB

serial/src/org/immutables/serial/Serial.java
I believe the intent here was that the Serial annotations not be retained in the compiled .class files, as the `@Serial` is annotated with Source retention and the annotations within are not copied to the generated immutable.
However, the retention meta-annotation does not apply to nested annotation definitions, so ultimately usages of `@Serial.Version` were being included in the generated classfile for the immutable _definition_, leading to problems finding the classfile if the Serial artifact was not on the classpath.
Here's a dump of the bytecode for an immutable definition with Serial.Version - you can clearly see the annotation is included by the compiler. (h/t @kmclarnon)
```
// class version 61.0 (61)
// access flags 0x601
public abstract interface com/hubspot/PersonIF {
// …
```
=> Use source retention for serial annotations

value-annotations/src/org/immutables/value/Generated.java
Update the generated annotation to appear in the JavaDoc headers for generated code. This is currently not the case, but is useful information to include to show users of a library using immutables that the type is generated rather than explicitly defined in the project source code.
=> Update Generated.java to be documented.

bom/pom.xml
As spotted in GH-1554, the `data` module is not currently in the bill of materials.
This change includes it so that this dependency can be managed via `<dependencyManagement/>` on the BOM module.
=> Include org.immutables:data in bill of materials

data/test/org/immutables/data/CustomNullableAnnotation.java, data/test/org/immutables/data/DataTest.java, data/test/org/immutables/data/Dtt.java, data/test/org/immutables/data/package-info.java, value-processor/src/org/immutables/value/processor/Datatypes.generator
Fixes GH-1557, where the use of documented annotations such as those in JSpecify resulted in the type representation including annotation names. This resulted in invalid code being generated for `TypeToken.of($TYPE$.class)` as the output would erroneously become `TypeToken.of(@SomeAnnotationHere $TYPE$.class)`, which is invalid Java syntax.
=> GH-1557: Fix erroneous code generation for TypeTokens of raw annotated types

value-processor/src/org/immutables/value/processor/Immutables.generator
This change-set should annotate final stage builder interfaces (`BuildFinal`) with [CanIgnoreReturnValue](https://errorprone.info/api/latest/com/google/errorprone/annotations/CanIgnoreReturnValue.html), and allow downstream projects using Error Prone to use Staged Builders without method chaining or disabling the [CheckReturnValue](https://errorprone.info/bugpattern/CheckReturnValue) bug-checker. This aligns with the existing implementation and "normal" and strict builders.
---
Aside from this change, I have a broader question:
We encountered this while trying to propagate optional values to default primitive members in our immutable models. For example, the following model `Foo` will produce a single builder method for `Foo#bar`, `BuildFinal bar(int bar)`, which cannot be called with an …
=> Final stage builder methods' return value should be ignorable

value-fixture/src/nonimmutables/huge/ChildOfHugeParents.java, value-fixture/src/nonimmutables/huge/HugeParentOne.java, value-fixture/src/nonimmutables/huge/HugeParentTwo.java, value-processor/src/org/immutables/value/processor/Immutables.generator, value-processor/src/org/immutables/value/processor/meta/FromSupertypesModel.java, value-processor/src/org/immutables/value/processor/meta/LongBits.java
This hopes to address #1572 by shortening the `mergeInternal` method by using methods, while maintaining the performance of the bit masking operators, especially for smaller data models.
Prior to this commit, our mergeInternal function that is created when a derived class is used as an Immutables target would check the possible types in a series of if blocks. However, this can lead to an explosion in the length of this method, especially for target classes with multiple parents. Long methods are concerning because it can exceed the JVM's default 8 KB limit for method compilation, forcing calls to remain interpreted.
Instead, generate specialized methods for each relevant subtype. This helps break up the monolithic mergeInternal method while not introducing too many method hops.
This …
=> Optimize mergeInternal generation with specialized methods per subtype

value-fixture/src/nonimmutables/SelfApplyingAnnotation.java, value-fixture/src/org/immutables/fixture/annotation/ExampleModelWithSelfApplyingAnnotation.java, value-fixture/test/org/immutables/fixture/annotation/PassAnnotationTest.java, value-processor/src/org/immutables/value/processor/meta/Annotations.java
This fixes https://github.com/immutables/immutables/issues/1600 which was a bug introduced by https://github.com/immutables/immutables/commit/3da32c580d3526584bd0b909cf891639b2cf214f.
I'm honestly not too sure about where to put the test to reproduce the bug and validate it. Ultimately all that matters is that we test the compilation of the class, but I couldn't figure out where other examples of tests like this would live, so I pattern-matched from the test added in that same commit.
Happy to update the test to whatever makes sense!
=> #1600 Stop infinite recursion for annotations applying to themselves
